FROM node:20-alpine
WORKDIR /app

# Instalar Chromium y dependencias necesarias para Puppeteer
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    nodejs \
    yarn

# Configurar variables de entorno para Puppeteer
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# copiar el resto del código
COPY . .

EXPOSE 2002

# comando de desarrollo con hot-reload
CMD ["npm", "run","start:dev"]
